// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHaDYawuAihP7_Mc25u7MKPQQv7KWnxM',
    appId: '1:12244963383:web:5a9df763a1cdb27b5cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    authDomain: 'my-social-app-d3394.firebaseapp.com',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
    measurementId: 'G-GG8FN8KP4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26t2B_IwvVvbkrriuPadKueVlnWjfrZM',
    appId: '1:12244963383:android:a5c96ab65acc62265cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGw5hb7k2MGep1Jcke52s5FgWuJ_btvcc',
    appId: '1:12244963383:ios:890f30bded14ac465cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGw5hb7k2MGep1Jcke52s5FgWuJ_btvcc',
    appId: '1:12244963383:ios:890f30bded14ac465cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEHaDYawuAihP7_Mc25u7MKPQQv7KWnxM',
    appId: '1:12244963383:web:581bd86f4fb6ea1d5cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    authDomain: 'my-social-app-d3394.firebaseapp.com',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
    measurementId: 'G-CZHTMXN4JR',
  );
}
