// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [ProdFirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHaDYawuAihP7_Mc25u7MKPQQv7KWnxM',
    appId: '1:12244963383:web:37ef2774d729235b5cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    authDomain: 'my-social-app-d3394.firebaseapp.com',
    databaseURL:
        'https://my-social-app-d3394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
    measurementId: 'G-B4MG6YBM0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26t2B_IwvVvbkrriuPadKueVlnWjfrZM',
    appId: '1:12244963383:android:3460d04073a19ead5cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    databaseURL:
        'https://my-social-app-d3394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGw5hb7k2MGep1Jcke52s5FgWuJ_btvcc',
    appId: '1:12244963383:ios:6685d152ebb04edc5cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    databaseURL:
        'https://my-social-app-d3394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
    androidClientId:
        '12244963383-4lao9rsb39lkfb9l6q9lrdur4i3hso4c.apps.googleusercontent.com',
    iosClientId:
        '12244963383-2am5aqkngjj9i4122ur1srlu7kp3vs6e.apps.googleusercontent.com',
    iosBundleId: 'in.mybanjara.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGw5hb7k2MGep1Jcke52s5FgWuJ_btvcc',
    appId: '1:12244963383:ios:d6d71f2005333b735cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    databaseURL:
        'https://my-social-app-d3394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
    androidClientId:
        '12244963383-4lao9rsb39lkfb9l6q9lrdur4i3hso4c.apps.googleusercontent.com',
    iosClientId:
        '12244963383-sfi57fopjcru5023uc65du7s3ejpcd3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEHaDYawuAihP7_Mc25u7MKPQQv7KWnxM',
    appId: '1:12244963383:web:943cfc6aa406648e5cafb2',
    messagingSenderId: '12244963383',
    projectId: 'my-social-app-d3394',
    authDomain: 'my-social-app-d3394.firebaseapp.com',
    databaseURL:
        'https://my-social-app-d3394-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'my-social-app-d3394.firebasestorage.app',
    measurementId: 'G-1WQ6DKVE5E',
  );
}
