// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGojJvjZob5F0OvL5sE7NQYXkGAtaVT1E',
    appId: '1:202576424225:web:3e6fe23fc2fd63db92e260',
    messagingSenderId: '202576424225',
    projectId: 'mybanjara-dev',
    authDomain: 'mybanjara-dev.firebaseapp.com',
    storageBucket: 'mybanjara-dev.firebasestorage.app',
    measurementId: 'G-TFFJH9FE2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwO50seSfz-3oqpsGBPygCeStmtMAtmgw',
    appId: '1:202576424225:android:3d60f1b0e3b7bf4192e260',
    messagingSenderId: '202576424225',
    projectId: 'mybanjara-dev',
    storageBucket: 'mybanjara-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD_2c8Vxjf6iJ6sPY4aqmvERX-PnO_US0',
    appId: '1:202576424225:ios:d4642f9c478a288992e260',
    messagingSenderId: '202576424225',
    projectId: 'mybanjara-dev',
    storageBucket: 'mybanjara-dev.firebasestorage.app',
    iosBundleId: 'in.mybanjara.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD_2c8Vxjf6iJ6sPY4aqmvERX-PnO_US0',
    appId: '1:202576424225:ios:6412c853a0c228de92e260',
    messagingSenderId: '202576424225',
    projectId: 'mybanjara-dev',
    storageBucket: 'mybanjara-dev.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGojJvjZob5F0OvL5sE7NQYXkGAtaVT1E',
    appId: '1:202576424225:web:d7a40cd4cd3d3e1692e260',
    messagingSenderId: '202576424225',
    projectId: 'mybanjara-dev',
    authDomain: 'mybanjara-dev.firebaseapp.com',
    storageBucket: 'mybanjara-dev.firebasestorage.app',
    measurementId: 'G-RF4C70JNQB',
  );
}
